import { type Metadata } from 'next';
import { Menu } from 'lucide-react';
import { Toaster } from 'react-hot-toast';
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';
import { Geist, Geist_Mono } from 'next/font/google';
import Image from 'next/image';
import './globals.css';
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header className="fixed top-0 left-0 right-0 z-50 flex justify-between items-center p-4 gap-4 h-16 text-black bg-white shadow">
            <div>
              <nav className="flex items-center gap-4">
                <Link href="/dashboard" className="text-lg font-semibold">
                  <Menu />
                </Link>
              </nav>
            </div>
            <div>
              <Link href="/" className="flex items-center gap-2">
                <Image
                  src="/logo-growthub.png"
                  width={150}
                  height={50}
                  alt="Mobilize"
                />
              </Link>
            </div>
            <div>
              <SignedOut>
                <SignInButton />
                <SignUpButton />
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </div>
          </header>

          {children}
          <Toaster position="top-right" />
        </body>
      </html>
    </ClerkProvider>
  );
}
